import type {Metadata} from "next";
import {Host_Grotesk} from "next/font/google";
import "./globals.css";
import {SpeedInsights} from "@vercel/speed-insights/next";
import {Toaster} from "sonner";

const hostGrotesk = Host_Grotesk({
    variable: "--font-host-grotesk",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Pocket Concerts - Registration",
    description: "Generated by create next app",
    icons: {
        icon: "/pocketConcertsLogo.jpg",
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${hostGrotesk.variable} antialiased`}>
        {children}
        <SpeedInsights/>
        <Toaster/>
        </body>
        </html>
    );
}
